### ISSUE TITLE
will dbus-1 poison capi-dbus?

### ISSUE THREAD

**Issue by zeerd** [GENIVI/capicxx-dbus-runtime#6]
As i known , the license of dbus-1 is gpl 2.0, the capi-dbus is linking to dbus-1. 
So mpl license is ok for this situation?

**Comment by gunnarx** [comment]
I think your main problem could be that your information is incomplete.  The [COPYING file](https://cgit.freedesktop.org/dbus/dbus/tree/COPYING) for D-Bus clarifies that you have a _choice_ between GPL and the Academic Free License. 

Another minor detail - the COPYING file does not say that it is gpl 2.0, it actually specifies "2.0... or any later version", which can be written as "GPL-2.0+"

Overall it cannot be answered without knowing what you mean by being **ok** (and "for this situation" - which situation is that?).  Or what the title means by "poison".   But if you wanted to understand what it means to combine MPLv2 and _GPL_ licensed code, then read the FSF opinion about compatibility between MPLv2 and GPL here:  https://www.gnu.org/licenses/license-list.en.html#MPL-2.0

On the other hand, if you do not want to follow the GPL license conditions, in this case it seems you could choose to apply the Academic Free License conditions instead - but please note that I cannot give you legal advice.  You/your company always need to evaluate and decide.

**Comment by zeerd** [comment]
Thank you , i will check those.
