### ISSUE TITLE
Patching issues with latest DBUS 1.12

### ISSUE THREAD

**Issue by ploughpuff** [GENIVI/capicxx-dbus-runtime#9]
The most recent stable version of DBUS is currently 1.12.2:
https://dbus.freedesktop.org/releases/dbus/

It seems the patches available from capixx-dbus-runtime/src/dbus-patches/ are applied to the DBUS source without observable issues, but compilation (make) fails with:
"undefined reference to '_dbus_check_is_valid_signature'

Please either update the patch files or indicate in the readme which versions of DBUS are compatible.

**Comment by GenivivSOMEIPmaintainer** [comment]
Patches have been updated with CommonAPI-D-Bus runtime 3.1.12.13.

**Comment by sashko** [comment]
@GenivivSOMEIPmaintainer we need clarification on where to obtain this release from -- the latest one seems to be 3.1.12.7.
